[package]
name = "uvth-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
uvth = { path = ".." }
threadpool = "1.7"
criterion = "0.2"

[[bench]]
name = "threadpool"
harness = false
